import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });
import { Inter } from "next/font/google";

import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Praxis Beck",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="de">
      <body className={`bg-gray-10 ${inter.className} hide-scrollbar::-webkit-scrollbar hide-scrollbar`}>
        <header>
          <Navbar/>
        </header>

        <main className="pt-24 relative overflow-hidden z-1">
        {children}
        </main>

        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
